import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },

  // Header hiển thị thông tin Admin
  headerMobile: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  adminProfileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  adminAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#16a34a",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#16a34a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  adminAvatarText: { fontSize: 20, fontWeight: "bold", color: "#fff" },
  greetingText: { fontSize: 12, color: "#64748b", marginBottom: 2 },
  adminName: { fontSize: 16, fontWeight: "800", color: "#0f172a" },
  adminEmail: { fontSize: 12, color: "#94a3b8" },

  // Nút đăng xuất tinh gọn
  logoutBtnIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fef2f2",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#fecaca",
  },

  scrollContainer: { flex: 1, padding: 16 },
  tabContent: { paddingBottom: 40 },
  errorBox: {
    backgroundColor: "#fef2f2",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  errorText: { color: "#dc2626", textAlign: "center", fontWeight: "bold" },
  sectionHeading: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#0f172a",
    marginTop: 10,
    marginBottom: 12,
  },

  // Dashboard Tab
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 20,
  },
  statCardMobile: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  halfCard: {
    width: "48%",
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  statCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  iconBox: { padding: 8, borderRadius: 12 },
  statTitle: { fontSize: 13, fontWeight: "600", color: "#64748b" },
  statValue: {
    fontSize: 24,
    fontWeight: "900",
    color: "#0f172a",
    marginBottom: 4,
  },
  statTrend: { fontSize: 12, color: "#10b981", fontWeight: "600" },
  cardContainer: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 16,
  },
  planItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  planLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  planIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  planText: { fontSize: 14, fontWeight: "600", color: "#334155" },
  planValue: { fontSize: 16, fontWeight: "bold", color: "#0f172a" },

  // Users Tab
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  searchInput: {
    flex: 1,
    height: 48,
    fontSize: 14,
    marginLeft: 8,
    outlineStyle: "none" as any,
  },
  searchBtn: {
    backgroundColor: "#16a34a",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  searchBtnText: { color: "#fff", fontWeight: "bold" },
  userCard: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#f1f5f9",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  userHeader: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#dbeafe",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarText: { fontSize: 18, fontWeight: "bold", color: "#2563eb" },
  userInfo: { flex: 1 },
  userName: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 2,
  },
  userEmail: { fontSize: 13, color: "#64748b" },
  userTags: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
  },
  tagRole: {
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  tagRoleText: { fontSize: 11, fontWeight: "bold", color: "#475569" },
  tagPlan: {
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  tagPlanText: { fontSize: 11, fontWeight: "bold", color: "#64748b" },
  userDate: {
    flex: 1,
    textAlign: "right",
    fontSize: 12,
    color: "#94a3b8",
    fontWeight: "500",
  },

  // Report Tab
  reportSummaryCard: {
    backgroundColor: "#1e293b",
    padding: 20,
    borderRadius: 20,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  reportSummaryTitle: {
    fontSize: 16,
    color: "#94a3b8",
    fontWeight: "600",
    marginBottom: 16,
  },
  reportRow: { flexDirection: "row", justifyContent: "space-between" },
  reportLabel: { fontSize: 12, color: "#cbd5e1", marginBottom: 4 },
  reportBigValue: { fontSize: 24, fontWeight: "900", color: "#fff" },
  monthCard: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  monthHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  monthText: { fontSize: 16, fontWeight: "bold", color: "#0f172a" },
  revenueBadge: {
    backgroundColor: "#dcfce3",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  revenueBadgeText: { fontSize: 14, fontWeight: "bold", color: "#16a34a" },
  monthDetails: { gap: 8 },
  detailItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  detailLabel: { fontSize: 14, color: "#64748b" },
  detailValue: { fontSize: 14, fontWeight: "600", color: "#334155" },

  // Feedback Tab
  feedbackTabs: {
    flexDirection: "row",
    backgroundColor: "#f1f5f9",
    padding: 4,
    borderRadius: 12,
    marginBottom: 16,
  },
  feedbackTabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
  },
  feedbackTabBtnActive: { backgroundColor: "#16a34a" },
  feedbackTabText: { fontSize: 14, fontWeight: "bold", color: "#64748b" },
  emptyText: {
    textAlign: "center",
    marginTop: 40,
    color: "#94a3b8",
    fontSize: 15,
  },
  feedbackCard: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  fbHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  fbName: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 2,
  },
  fbEmail: { fontSize: 13, color: "#64748b" },
  fbCategoryBadge: {
    backgroundColor: "#fef3c7",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  fbCategoryText: { fontSize: 11, fontWeight: "bold", color: "#d97706" },
  fbContentBox: {
    backgroundColor: "#f8fafc",
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  fbContentText: {
    fontSize: 14,
    color: "#334155",
    lineHeight: 22,
    marginBottom: 8,
  },
  fbDate: { fontSize: 11, color: "#94a3b8", textAlign: "right" },
  openReplyBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0fdf4",
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#bbf7d0",
    gap: 8,
  },
  openReplyText: { fontSize: 14, fontWeight: "bold", color: "#16a34a" },
  replyBox: { marginTop: 8 },
  replyInput: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    minHeight: 80,
    textAlignVertical: "top",
    marginBottom: 12,
  },
  replyActions: { flexDirection: "row", gap: 12 },
  cancelReplyBtn: {
    flex: 1,
    backgroundColor: "#f1f5f9",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
  },
  cancelReplyText: { fontSize: 14, fontWeight: "bold", color: "#64748b" },
  submitReplyBtn: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#16a34a",
    paddingVertical: 12,
    borderRadius: 10,
    gap: 8,
  },
  submitReplyText: { fontSize: 14, fontWeight: "bold", color: "#fff" },
  repliedBox: {
    backgroundColor: "#f0fdf4",
    padding: 12,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#16a34a",
  },
  repliedLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#16a34a",
    marginBottom: 4,
  },
  repliedContent: {
    fontSize: 14,
    color: "#15803d",
    marginBottom: 8,
    lineHeight: 20,
  },

  // Bottom Navigation Bar
  bottomBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    justifyContent: "space-around",
  },
  bottomTab: { alignItems: "center", justifyContent: "center", flex: 1 },
  bottomTabText: {
    fontSize: 11,
    color: "#94a3b8",
    marginTop: 4,
    fontWeight: "600",
  },
  bottomTabTextActive: { color: "#16a34a", fontWeight: "bold" },

  // CSS chấm đỏ thông báo
  notificationBadge: {
    position: "absolute",
    top: -4,
    right: -8,
    backgroundColor: "#ef4444",
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "#fff",
  },
  notificationText: { color: "#fff", fontSize: 10, fontWeight: "bold" },
});
