import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  centerBox: { flex: 1, justifyContent: "center", alignItems: "center" },

  floatingHeader: {
    position: "absolute",
    left: 16,
    right: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },

  coverSection: { width: "100%", height: 260, position: "relative" },
  coverImg: { width: "100%", height: "100%", resizeMode: "cover" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.25)",
  },

  infoCard: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: -40,
    borderRadius: 24,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
  },
  plantName: {
    fontSize: 24,
    fontWeight: "900",
    color: "#0f172a",
    marginBottom: 4,
  },
  plantCondition: { fontSize: 15, color: "#64748b", fontWeight: "600" },
  goalBadge: {
    backgroundColor: "#fef3c7",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  goalBadgeText: { color: "#d97706", fontWeight: "bold", fontSize: 13 },
  progressSection: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
  },
  progressLabel: { fontSize: 14, color: "#64748b", fontWeight: "bold" },
  progressValue: { fontSize: 15, color: "#16a34a", fontWeight: "900" },
  progressBarBg: {
    height: 12,
    backgroundColor: "#e2e8f0",
    borderRadius: 6,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#16a34a",
    borderRadius: 6,
  },

  tabContainer: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginTop: 20,
    backgroundColor: "#e2e8f0",
    borderRadius: 14,
    padding: 4,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    paddingVertical: 14,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    borderRadius: 12,
  },
  tabBtnActive: {
    backgroundColor: "#16a34a",
    shadowColor: "#16a34a",
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  tabText: { fontSize: 15, fontWeight: "bold", color: "#64748b" },
  tabTextActive: { color: "#fff" },

  contentArea: { padding: 16 },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 20,
  },
  roadmapTab: { position: "relative", paddingLeft: 10 },
  timelineLine: {
    position: "absolute",
    left: 23,
    top: 45,
    bottom: 20,
    width: 2,
    backgroundColor: "#cbd5e1",
  },
  taskItem: { flexDirection: "row", marginBottom: 24 },
  timelineDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#f1f5f9",
    borderWidth: 2,
    borderColor: "#cbd5e1",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
    marginTop: 10,
  },
  timelineDotDone: { backgroundColor: "#16a34a", borderColor: "#16a34a" },
  dotText: { fontSize: 12, fontWeight: "bold", color: "#64748b" },
  taskCard: {
    flex: 1,
    marginLeft: 16,
    backgroundColor: "#fff",
    padding: 18,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    elevation: 1,
  },
  taskCardDone: { opacity: 0.6, backgroundColor: "#f8fafc" },
  taskHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  taskDayTitle: { fontSize: 17, fontWeight: "bold", color: "#1e293b" },
  taskDate: { fontSize: 13, color: "#94a3b8", fontWeight: "600" },
  taskDetailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 10,
  },
  taskDetailText: { flex: 1, fontSize: 15, color: "#475569", lineHeight: 22 },

  checkinTab: { padding: 10 },
  checkinBox: {
    backgroundColor: "#fff",
    padding: 30,
    borderRadius: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    elevation: 2,
  },
  checkinTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#0f172a",
    marginTop: 16,
    marginBottom: 8,
  },
  checkinDesc: {
    fontSize: 15,
    color: "#64748b",
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 30,
  },
  cameraBtn: {
    flexDirection: "row",
    backgroundColor: "#16a34a",
    width: "100%",
    paddingVertical: 18,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    elevation: 3,
  },
  cameraBtnText: { color: "#fff", fontSize: 17, fontWeight: "bold" },
  warningBox: {
    flexDirection: "row",
    backgroundColor: "#fef3c7",
    padding: 16,
    borderRadius: 16,
    marginTop: 24,
    gap: 12,
  },
  warningText: {
    flex: 1,
    fontSize: 14,
    color: "#d97706",
    lineHeight: 22,
    fontWeight: "500",
  },
});
