import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 10,
    backgroundColor: "#fff",
  },
  headerLeft: { flexDirection: "row", alignItems: "center" },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    marginRight: 24,
  },
  iconBtn: { padding: 8 },
  modalContainer: { flex: 1, flexDirection: "row" },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  leftDrawer: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: width * 0.75,
    backgroundColor: "#1B5E20",
    shadowColor: "#000",
    shadowOffset: { width: 5, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 20,
  },
  sidebarContent: { flex: 1 },
  sidebarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  sidebarTitle: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  tabsContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.1)",
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabBtnActive: { borderBottomColor: "#86efac" },
  tabText: { fontSize: 13, color: "#9ca3af", fontWeight: "600" },
  tabTextActive: { color: "#86efac" },
  historyList: { flex: 1, paddingHorizontal: 16, paddingTop: 10 },
  emptySidebarTxt: {
    color: "#86efac",
    textAlign: "center",
    marginTop: 20,
    fontStyle: "italic",
    fontSize: 13,
  },
  newChatSidebarBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  newChatSidebarText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 10,
  },
  dateGroupHeader: {
    color: "rgba(134, 239, 172, 0.7)",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 16,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 12,
    marginBottom: 4,
  },
  historyItemActive: {
    backgroundColor: "rgba(134, 239, 172, 0.2)",
    borderRadius: 12,
  },
  historyText: { color: "#86efac", fontSize: 14, fontWeight: "500" },
  historyDate: { color: "#86efac", fontSize: 11, marginTop: 4, opacity: 0.8 },
  sidebarFooter: {
    paddingHorizontal: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.1)",
  },
  upgradeBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    padding: 12,
    borderRadius: 16,
  },
  upgradeIconWrapper: {
    width: 36,
    height: 36,
    backgroundColor: "#fef08a",
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  upgradeTitle: { fontSize: 15, fontWeight: "bold", color: "#fff" },
  upgradeSub: { fontSize: 12, color: "#86efac", marginTop: 2 },
  chatArea: { flex: 1, backgroundColor: "#fff" },
  scrollContent: { padding: 16, paddingBottom: 20 },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 100,
    paddingHorizontal: 20,
  },
  botAvatarLarge: {
    width: 70,
    height: 70,
    backgroundColor: "#dcfce3",
    borderRadius: 35,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 12,
  },
  emptyDesc: {
    fontSize: 15,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 24,
  },
  messageWrapper: {
    flexDirection: "row",
    marginBottom: 24,
    alignItems: "flex-end",
  },
  msgLeft: { justifyContent: "flex-start" },
  msgRight: { justifyContent: "flex-end" },
  botAvatarSmall: {
    width: 32,
    height: 32,
    backgroundColor: "#16a34a",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    marginBottom: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  userAvatarSmall: {
    width: 32,
    height: 32,
    backgroundColor: "#e5e7eb",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    marginBottom: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  messageContentUser: { alignItems: "flex-end", maxWidth: "80%" },
  messageContentBot: { alignItems: "flex-start", maxWidth: "80%" },
  senderLabel: {
    fontSize: 12,
    color: "#9ca3af",
    marginBottom: 4,
    paddingHorizontal: 4,
  },
  messageBubble: {
    padding: 14,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  bubbleUser: { backgroundColor: "#16a34a", borderBottomRightRadius: 4 },
  bubbleBot: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#f3f4f6",
    borderBottomLeftRadius: 4,
  },
  msgText: { fontSize: 15, lineHeight: 24 },
  textUser: { color: "#fff" },
  textBot: { color: "#374151" },
  scanResultContainer: { padding: 14, maxWidth: "100%" },
  diagnosisTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 12,
  },
  diseaseSection: {
    backgroundColor: "#f0fdf4",
    padding: 12,
    borderRadius: 10,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#16a34a",
  },
  diseaseLabel: { fontSize: 13, fontWeight: "600", color: "#374151" },
  diseaseName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#16a34a",
    marginTop: 4,
  },
  confidenceText: { fontSize: 13, color: "#6b7280", marginTop: 6 },
  symptomsSection: { marginBottom: 12 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 8,
  },
  bulletText: { fontSize: 13, color: "#374151", lineHeight: 20, marginLeft: 6 },
  treatmentsSection: {
    backgroundColor: "#fff8f0",
    padding: 12,
    borderRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: "#dc2626",
  },
  treatmentSubSection: { marginBottom: 12 },
  treatmentSubTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#dc2626",
    marginBottom: 6,
  },
  treatmentText: {
    fontSize: 12,
    color: "#374151",
    lineHeight: 18,
    marginBottom: 6,
  },
  msgImage: {
    width: 220,
    height: 220,
    borderRadius: 12,
    marginBottom: 10,
    resizeMode: "cover",
  },
  inputContainer: {
    backgroundColor: "#fff",
    paddingTop: 10,
    paddingHorizontal: 16,
  },
  inputWrapper: { width: "100%", maxWidth: 600, alignSelf: "center" },
  previewContainer: {
    position: "relative",
    alignSelf: "flex-start",
    marginBottom: 10,
  },
  previewImg: {
    width: 64,
    height: 64,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  removePreviewBtn: {
    position: "absolute",
    top: -6,
    right: -6,
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 4,
  },
  inputBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: "#fff",
    borderRadius: 30,
    paddingHorizontal: 6,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#d1d5db",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  actionBtn: { padding: 10, justifyContent: "center", alignItems: "center" },
  textInput: {
    flex: 1,
    maxHeight: 120,
    minHeight: 40,
    fontSize: 15,
    color: "#111827",
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 4,
    outlineStyle: "none" as any,
  },
  sendBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
    marginLeft: 4,
  },
  sendBtnActive: {
    backgroundColor: "#16a34a",
    shadowColor: "#16a34a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  sendBtnDisabled: { backgroundColor: "#f3f4f6" },
  disclaimer: {
    textAlign: "center",
    fontSize: 11,
    color: "#9ca3af",
    marginTop: 8,
  },
});
