import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fafaf9" },
  scrollContent: { paddingBottom: 100 },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 10,
    backgroundColor: "#fafaf9",
  },
  logoWrapper: { flexDirection: "row", alignItems: "center", gap: 8 },
  logoIconBox: { backgroundColor: "#2e7d32", padding: 6, borderRadius: 8 },
  logoTitle: { fontSize: 20, fontWeight: "800", color: "#111827" },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 12 },
  bellBtn: { position: "relative", padding: 4 },
  bellDot: {
    position: "absolute",
    top: 4,
    right: 6,
    width: 10,
    height: 10,
    backgroundColor: "#ef4444",
    borderRadius: 5,
    borderWidth: 2,
    borderColor: "#fafaf9",
  },
  avatarBtnNavbar: { padding: 4 },
  avatarRingSmall: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  avatarCircleSmall: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#dc2626",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarTextSmall: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  modalContainer: { flex: 1, flexDirection: "row" },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  drawer: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: width * 0.75,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: -5, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 20,
  },
  menuContent: { flex: 1 },
  menuHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  menuTitle: { fontSize: 16, fontWeight: "600", color: "#111827" },
  closeBtn: { padding: 4 },
  userInfoSection: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
    backgroundColor: "#fafaf9",
  },
  avatarRingLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    marginRight: 12,
  },
  avatarCircleLarge: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#dc2626",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarTextLarge: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  userDetails: { flex: 1, paddingRight: 10 },
  userName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 2,
  },
  userEmail: { fontSize: 13, color: "#6b7280", marginBottom: 4 },
  menuLinks: { flex: 1, paddingHorizontal: 24, paddingTop: 10 },
  adminMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fef2f2",
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginBottom: 10,
    gap: 10,
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  adminMenuText: { fontSize: 15, color: "#dc2626", fontWeight: "bold" },
  menuItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f9fafb",
  },
  menuItemText: { fontSize: 16, color: "#374151", fontWeight: "600" },
  divider: { height: 1, backgroundColor: "#f3f4f6", marginVertical: 10 },
  menuItemWithIcon: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    gap: 12,
  },
  menuItemTextIcon: { fontSize: 16, color: "#4b5563", fontWeight: "500" },
  menuFooter: {
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: "#f3f4f6",
    paddingTop: 20,
  },
  menuLogoutBtn: {
    flexDirection: "row",
    backgroundColor: "#fef2f2",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  menuLogoutText: { color: "#ef4444", fontSize: 15, fontWeight: "bold" },
  heroSection: {
    paddingHorizontal: 20,
    paddingTop: 10,
    alignItems: "flex-start",
  },
  badgeWeb: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0fdf4",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#dcfce3",
    marginBottom: 15,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#16a34a",
    marginRight: 8,
  },
  badgeText: { fontSize: 12, color: "#16a34a", fontWeight: "600" },
  mainTitle: {
    fontSize: 42,
    fontWeight: "900",
    color: "#111827",
    lineHeight: 48,
    letterSpacing: -1,
  },
  greenTitle: { color: "#16a34a" },
  description: {
    fontSize: 16,
    color: "#4b5563",
    lineHeight: 24,
    marginTop: 15,
    marginBottom: 25,
  },
  buttonGroup: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 30,
  },
  primaryBtn: {
    backgroundColor: "#16a34a",
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    elevation: 2,
  },
  primaryBtnText: { color: "#fff", fontWeight: "bold", fontSize: 15 },
  featuresSection: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 40,
    backgroundColor: "#fafaf9",
  },
  featuresHeader: { alignItems: "center", marginBottom: 30 },
  featuresEyebrow: {
    color: "#16a34a",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 8,
  },
  featuresTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
    textAlign: "center",
    lineHeight: 32,
    marginBottom: 12,
  },
  featuresList: { gap: 16 },
  featureCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#f3f4f6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  featureIconBox: {
    width: 56,
    height: 56,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  featureItemTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 4,
  },
  featureItemDesc: { fontSize: 13, color: "#6b7280", lineHeight: 20 },
  footer: { paddingVertical: 20, alignItems: "center" },
  footerText: { fontSize: 12, color: "#9ca3af" },
});
