import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8fafc",
  },
  loadingText: { marginTop: 12, color: "#64748b", fontSize: 15 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  backBtn: { width: 40, height: 40, justifyContent: "center" },
  locationWrapper: { flexDirection: "row", alignItems: "center", gap: 6 },
  locationText: { fontSize: 18, fontWeight: "bold", color: "#1e293b" },

  filterContainer: {
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  filterScroll: { paddingHorizontal: 16, gap: 10 },
  filterBtn: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "transparent",
  },
  filterBtnActive: { backgroundColor: "#dcfce3", borderColor: "#22c55e" },
  filterBtnText: { color: "#64748b", fontWeight: "600", fontSize: 14 },
  filterBtnTextActive: { color: "#15803d" },

  scrollContent: {
    padding: 16,
    maxWidth: 600,
    width: "100%",
    alignSelf: "center",
  },

  heroCard: {
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  heroMain: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginBottom: 24,
  },
  heroTextGroup: { alignItems: "flex-start" },
  weatherIconHuge: { width: 130, height: 130, marginRight: -10 },
  tempHuge: { fontSize: 72, fontWeight: "900", color: "#fff", lineHeight: 76 },
  weatherDesc: {
    fontSize: 18,
    color: "#e0f2fe",
    fontWeight: "600",
    textTransform: "capitalize",
    marginTop: 4,
  },

  statsGridRow: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 16,
    padding: 16,
    justifyContent: "space-between",
  },
  statItemRow: { alignItems: "center", gap: 4 },
  statValueRow: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    marginTop: 4,
  },
  statLabelRow: { color: "#e0f2fe", fontSize: 13 },

  goldenHourCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#ecfdf5",
    padding: 16,
    borderRadius: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#a7f3d0",
  },
  goldenHourLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    paddingRight: 10,
  },
  goldenIconBox: {
    backgroundColor: "#d1fae5",
    padding: 10,
    borderRadius: 12,
    marginRight: 12,
  },
  goldenTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#065f46",
    marginBottom: 2,
  },
  goldenDesc: { fontSize: 13, color: "#047857", lineHeight: 18 },
  goldenTimeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  goldenTimeText: { fontSize: 15, fontWeight: "bold", color: "#059669" },

  section: { marginBottom: 24 },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 18, fontWeight: "800", color: "#0f172a" },

  // Styles cho Cụm Chỉ Số Mở Rộng
  summaryBox: {
    backgroundColor: "#f0fdfa",
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#ccfbf1",
  },
  summaryText: {
    color: "#0f766e",
    fontSize: 15,
    fontWeight: "500",
    lineHeight: 22,
  },
  extendedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  extendedItem: {
    width: "48%",
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  extendedLabel: {
    fontSize: 13,
    color: "#64748b",
    fontWeight: "500",
    marginBottom: 2,
  },
  extendedValue: { fontSize: 15, fontWeight: "800", color: "#1e293b" },

  dateTabsScroll: { gap: 10, paddingVertical: 4 },
  dateTab: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
    minWidth: 80,
  },
  dateTabActive: { backgroundColor: "#2563eb", borderColor: "#2563eb" },
  dateTabText: { fontSize: 14, fontWeight: "600", color: "#475569" },
  dateTabTextActive: { color: "#fff" },

  adviceCard: {
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
  },
  cardWarning: { backgroundColor: "#fef2f2", borderColor: "#fecaca" },
  cardRecommend: { backgroundColor: "#f0fdf4", borderColor: "#bbf7d0" },
  cardInfo: { backgroundColor: "#eff6ff", borderColor: "#bfdbfe" },
  adviceHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  adviceTitle: { fontSize: 16, fontWeight: "800", color: "#1e293b", flex: 1 },
  adviceMessage: { fontSize: 14, color: "#334155", lineHeight: 22 },

  hourlyScroll: { gap: 12 },
  hourlyItem: {
    backgroundColor: "#fff",
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 16,
    alignItems: "center",
    width: 80,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  hourlyTime: {
    fontSize: 13,
    color: "#64748b",
    marginBottom: 8,
    fontWeight: "600",
  },
  hourlyIcon: { width: 48, height: 48 },
  hourlyTemp: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1e293b",
    marginTop: 4,
  },
  popBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginTop: 6,
    backgroundColor: "#e0f2fe",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 10,
  },
  popText: { fontSize: 11, color: "#0284c7", fontWeight: "bold" },

  errorBox: {
    backgroundColor: "#fef2f2",
    padding: 20,
    borderRadius: 16,
    alignItems: "center",
    marginTop: 40,
  },
  errorText: {
    color: "#dc2626",
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 22,
  },
  retryBtn: {
    backgroundColor: "#ef4444",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  retryText: { color: "#fff", fontWeight: "bold" },
});
